sudo: false
language: node_js
node_js:
  - v10.15.3
  - v11.14.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - CXX="g++-4.8" CC="gcc-4.8"
after_script:
  - npm run covarage
